### PR TITLE
fix `nameFunc`

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by cvan** [comment]
@jlongster can you please merge in this bad boy?

**Comment by jlongster** [comment]
I wonder if there's a way to test grunt tasks. Sorry for letting this sit.

**Comment by cvan** [comment]
no worries, mane - thanks! /me wonders too

**Comment by jlongster** [comment]
haha. This is the _one_ time I didn't test before pushing. damnit @cvan.

I'll fix it, it's probably not hard.

**Comment by jlongster** [comment]
I reverted your initial commit. It was correct originally. What was your problem with it?

**Pull request merged**
