### PR TITLE
added support for "name" option (fixes #1)

### PR DESCRIPTION
**Pull request by mnpenner**

### CODE REVIEW

**Comment by dkleehammer** [comment]
Is this gonna to be merged to the master anytime soon?  I'd really like to get the templates compiled with a name that the client can easily use.

**Comment by jlongster** [comment]
Really sorry about this! Turns out I wasn't receiving notifications for this repo. Thanks!

**Comment by jlongster** [comment]
BTW, the latest nunjucks automatically replaces \\ with / for you, and another PR adds the `baseDir` option and it will strip that from the filename.

**Comment by dkleehammer** [comment]
Great, thanks!

**Pull request merged**
