### PR TITLE
add "rename" option, bump nunjucks dep to 1.0.0 to fix runtime error

### PR DESCRIPTION
**Pull request by chrisdanford**
## add "rename" option

This adds a task option `rename` that is called once per template file and used to populate the `name` option to `precompile`.

Example:

```
var path = require('path');
...
nunjucks: {
  precompile: {
    options: {
      rename: function(src) {
         return path.basename(src);
      },
  },
```
## bump nunjucks dep to 1.0.0 to fix runtime error

Before upgrading Nunjucks to 1.0.0, I was hitting the following error:

screen shot 2013-10-29 at 4 29 53 pm

### CODE REVIEW

**Comment by chrisdanford** [comment]
ping.  Not urgent though.

**Comment by mnpenner** [comment]
I too would like to see this feature. Alternatively, the `precompile` function already allows a `name` option -- perhaps you should allow it to take a function as input as well?

**Comment by mnpenner** [comment]
I think this is actually a pretty serious issue. I'm trying to use my templates both client-side and server-side but I can't do it because the names won't match up. On the client, it expects everything to begin with `templates/` but on the server it doesn't. This means something like this:

```
{% extends 'layouts/main.njs' %}
```

Won't work on the client because `main.njs` actually lives in `templates/layouts/main.njs`.

I did some digging through the source to figure out how I might fix this, and found that Nunjucks actually supports precompiling a directory and it will make all paths relative to that (like I want). However, it's got this [really weird filter](https://github.com/jlongster/nunjucks/blob/master/src/precompile.js#L56-L77) going on that will actually exclude all your templates _by default_. The matching doesn't appear to be a minimatch glob or anything; I'm not quite sure what it is, but I found out I can work around it so it always passes by giving it an array containing only an empty string. Thus my Gruntfile now looks like this:

``` javascript
nunjucks: {
    precompile: {
        src: 'templates',
        dest: 'cache/templates.js',
        options: {
            env: require('./server/nunjucks-environment'),
            include: [''],
        }
    }
},
```

Which gives me very nearly what I want, except the filepaths are broken on Windows. For example, it generates:

``` javascript
...
(function() {(window.nunjucksPrecompiled = window.nunjucksPrecompiled || {})["layouts\main.njs"] = (function() {function root(env, context, frame, runtime, cb) {
...
```

Notice the `\` is the "wrong" way. `\m` isn't a valid escape sequence. It should either be escaped, or preferably, standardized to a forward-slash.

**Comment by mnpenner** [comment]
Sorry for all the spam, but I patched the task to support a `name` function. Here's `grunt-nunjucks/tasks/nunjucks.js` in its entirety:

``` javascript
/*
 * grunt-nunjucks
 * https://github.com/jlongster/nunjucks-grunt
 *
 * Copyright (c) 2013 James Long
 * Licensed under the MIT license.
 */

'use strict';

module.exports = function (grunt) {
    var nunjucks = require('nunjucks');
    var lib = require('nunjucks/src/lib');

    grunt.registerMultiTask('nunjucks', 'Precompile nunjucks', function () {
        // Merge task-specific and/or target-specific options with these defaults.
        var opts = this.options({
            asFunction: false,
            env: null
        });

        var nameFunc = lib.isFunction(opts.name) ? opts.name : function(filepath) {
            return filepath.split('\\').join('/');
        }

        var files = this.files.forEach(function (f) {
            var src = f.src.filter(function (filepath) {
                if (!grunt.file.exists(filepath)) {
                    grunt.log.warn('Source file "' + filepath + '" not found.');
                    return false;
                } else {
                    return true;
                }
            }).map(function (filepath) {
                opts.name = nameFunc(filepath);
                return nunjucks.precompile(filepath, opts);
            }).join('');

            grunt.file.write(f.dest, src);
            grunt.log.writeln('File "' + f.dest + '" created.');
        });
    });
};
```

Which can be used like this:

``` javascript
nunjucks: {
    precompile: {
        src: 'templates/**/*.njs',
        dest: 'cache/templates.js',
        options: {
            env: require('./server/nunjucks-environment'),
            name: function(filename) {
                return path.relative('templates/',filename).split('\\').join('/');
            }
        }
    }
},
```

Note string escaping issue should still be handled on the Nunjucks side, however. Also, this name function would be better if were implemented somewhere [in here](https://github.com/jlongster/nunjucks/blob/master/src/precompile.js#L20) but I didn't want to monkey with the Nunjucks source.

**Pull request closed without merging**
